import 'package:customer/features/home/domain/entities/category_entity.dart';
import 'package:customer/features/home/domain/entities/provider_summary_entity.dart';
import 'package:customer/features/services/domain/entities/service_entity.dart';

class DemoData {
  static List<CategoryEntity> get demoCategories => [
    const CategoryEntity(id: 'cleaning', name: 'Cleaning', iconName: 'cleaning_services', color: '#4CAF50', iconUrl: '', sortOrder: 1),
    const CategoryEntity(id: 'ac_repair', name: 'AC Repair', iconName: 'ac_unit', color: '#2196F3', iconUrl: '', sortOrder: 2),
    const CategoryEntity(id: 'plumbing', name: 'Plumbing', iconName: 'plumbing', color: '#FF9800', iconUrl: '', sortOrder: 3),
    const CategoryEntity(id: 'electrical', name: 'Electrical', iconName: 'electrical_services', color: '#F44336', iconUrl: '', sortOrder: 4),
    const CategoryEntity(id: 'beauty', name: 'Beauty & Salon', iconName: 'content_cut', color: '#E91E63', iconUrl: '', sortOrder: 5),
  ];

  static List<ProviderSummaryEntity> get demoProviders => [
    const ProviderSummaryEntity(
      id: 'demo_1',
      businessName: 'CleanPro Services',
      rating: 4.8,
      reviewCount: 124,
      photoUrl: '',
      categories: ['Cleaning'],
      isVerified: true,
      distance: 1.2,
      completedJobs: 340,
      serviceArea: 'Downtown',
      isActive: true,
      onboardingStatus: 'approved',
    ),
    const ProviderSummaryEntity(
      id: 'demo_2',
      businessName: 'CoolAir Technicians',
      rating: 4.6,
      reviewCount: 89,
      photoUrl: '',
      categories: ['AC Repair'],
      isVerified: true,
      distance: 2.4,
      completedJobs: 215,
      serviceArea: 'Uptown',
      isActive: true,
      onboardingStatus: 'approved',
    ),
    const ProviderSummaryEntity(
      id: 'demo_3',
      businessName: 'QuickFix Plumbers',
      rating: 4.7,
      reviewCount: 67,
      photoUrl: '',
      categories: ['Plumbing'],
      isVerified: true,
      distance: 0.8,
      completedJobs: 189,
      serviceArea: 'Midtown',
      isActive: true,
      onboardingStatus: 'approved',
    ),
    const ProviderSummaryEntity(
      id: 'demo_4',
      businessName: 'PowerSpark Electricals',
      rating: 4.9,
      reviewCount: 203,
      photoUrl: '',
      categories: ['Electrical'],
      isVerified: true,
      distance: 3.1,
      completedJobs: 456,
      serviceArea: 'West Side',
      isActive: true,
      onboardingStatus: 'approved',
    ),
    const ProviderSummaryEntity(
      id: 'demo_5',
      businessName: 'Glamour Beauty Studio',
      rating: 4.5,
      reviewCount: 156,
      photoUrl: '',
      categories: ['Beauty & Salon'],
      isVerified: false,
      distance: 1.9,
      completedJobs: 278,
      serviceArea: 'East Side',
      isActive: true,
      onboardingStatus: 'approved',
    ),
  ];

  static List<ServiceEntity> get popularServices => [
    const ServiceEntity(
      id: 'pop_1',
      name: 'Full House Cleaning',
      description: 'Complete deep cleaning of your entire home by trained professionals.',
      categoryId: 'cleaning',
      categoryName: 'Cleaning',
      providerId: 'demo_1',
      providerName: 'CleanPro Services',
      basePrice: 799,
      discountPrice: 599,
      duration: 180,
      rating: 4.8,
      reviewCount: 124,
      isActive: true,
      imageUrl: '',
      bookingCount: 150,
    ),
    const ServiceEntity(
      id: 'pop_2',
      name: 'AC Service & Gas Refill',
      description: 'Complete AC servicing including cleaning, gas top-up and performance check.',
      categoryId: 'ac_repair',
      categoryName: 'AC Repair',
      providerId: 'demo_2',
      providerName: 'CoolAir Technicians',
      basePrice: 599,
      discountPrice: 399,
      duration: 90,
      rating: 4.6,
      reviewCount: 89,
      isActive: true,
      imageUrl: '',
      bookingCount: 120,
    ),
    const ServiceEntity(
      id: 'pop_3',
      name: 'Tap & Pipe Repair',
      description: 'Fix leaking taps, pipes, and drainage issues quickly.',
      categoryId: 'plumbing',
      categoryName: 'Plumbing',
      providerId: 'demo_3',
      providerName: 'QuickFix Plumbers',
      basePrice: 349,
      discountPrice: 249,
      duration: 60,
      rating: 4.7,
      reviewCount: 67,
      isActive: true,
      imageUrl: '',
      bookingCount: 85,
    ),
    const ServiceEntity(
      id: 'pop_4',
      name: 'Switchboard & Wiring Fix',
      description: 'Safe and professional electrical repairs for home and office.',
      categoryId: 'electrical',
      categoryName: 'Electrical',
      providerId: 'demo_4',
      providerName: 'PowerSpark Electricals',
      basePrice: 299,
      discountPrice: 199,
      duration: 45,
      rating: 4.9,
      reviewCount: 203,
      isActive: true,
      imageUrl: '',
      bookingCount: 200,
    ),
    const ServiceEntity(
      id: 'pop_5',
      name: 'Haircut & Styling',
      description: 'Professional haircut and styling at your doorstep.',
      categoryId: 'beauty',
      categoryName: 'Beauty & Salon',
      providerId: 'demo_5',
      providerName: 'Glamour Beauty Studio',
      basePrice: 399,
      discountPrice: 299,
      duration: 60,
      rating: 4.5,
      reviewCount: 156,
      isActive: true,
      imageUrl: '',
      bookingCount: 95,
    ),
  ];
}
